<?php

namespace Database\Seeders;

use App\Models\chartOfAccounts;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use function Ramsey\Uuid\v1;

class ChartOfAccountsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        chartOfAccounts::insert(
            [
                0 => [
                    'id' => 1,
                    'name' => 'Owner Investment / Drawings',
                    'chart_of_accounts_subtypes_id' => '28',
                    'code' => null,
                    'description' => 'Owner investment represents the amount of money or assets you put into your business, either to start the business or keep it running. An owner\'s draw is a direct withdrawal from business cash or assets for your personal use.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                1 => [
                    'id' => 2,
                    'name' => 'Owner\'s Equity',
                    'chart_of_accounts_subtypes_id' => '29',
                    'code' => null,
                    'description' => 'Owner\'s equity is what remains after you subtract business liabilities from business assets. In other words, it\'s what\'s left over for you if you sell all your assets and pay all your debts.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                2 => [
                    'id' => 3,
                    'name' => 'Consulting Income',
                    'chart_of_accounts_subtypes_id' => '23',
                    'code' => null,
                    'description' => 'Money your business receives by providing consulting services to your customers.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                3 => [
                    'id' => 4,
                    'name' => 'Sales',
                    'chart_of_accounts_subtypes_id' => '23',
                    'code' => null,
                    'description' => 'Money your business receives by providing consulting services to your customers.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                4 => [
                    'id' => 5,
                    'name' => 'Uncategorized Income',
                    'chart_of_accounts_subtypes_id' => '26',
                    'code' => null,
                    'description' => 'Income you haven\'t categorized yet. Categorize it now to keep your records accurate.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                5 => [
                    'id' => 6,
                    'name' => 'Gain on Foreign Exchange',
                    'chart_of_accounts_subtypes_id' => '27',
                    'code' => null,
                    'description' => 'Foreign exchange gains happen when the exchange rate between your business\'s home currency and a foreign currency transaction changes and results in a gain. This can happen in the time between a transaction being entered in Anvil and being settled, for example, between when you send an invoice and when your customer pays it. This can affect foreign currency invoice payments, bill payments, or foreign currency held in your bank account.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                6 => [
                    'id' => 7,
                    'name' => 'Accounts Payable',
                    'chart_of_accounts_subtypes_id' => '11',
                    'code' => null,
                    'description' => '',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                7 => [
                    'id' => 8,
                    'name' => 'Accounts Receivable',
                    'chart_of_accounts_subtypes_id' => '2',
                    'code' => null,
                    'description' => '',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                8 => [
                    'id' => 9,
                    'name' => 'Accounting Fees',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Accounting or bookkeeping services for your business.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                9 => [
                    'id' => 10,
                    'name' => 'Advertising & Promotion',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Advertising or other costs to promote your business. Includes web or social media promotion.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                10 => [
                    'id' => 11,
                    'name' => 'Bank Service Charges',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Fees you pay to your bank like transaction charges, monthly charges, and overdraft charges.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                11 => [
                    'id' => 12,
                    'name' => 'Computer – Hardware',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Desktop or laptop computers, mobile phones, tablets, and accessories used for your business.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                12 => [
                    'id' => 13,
                    'name' => 'Computer – Hosting',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Fees for web storage and access, like hosting your business website or app.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                13 => [
                    'id' => 14,
                    'name' => 'Computer – Internet',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Internet services for your business. Does not include data access for mobile devices.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                14 => [
                    'id' => 15,
                    'name' => 'Computer – Software',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Apps, software, and web or cloud services you use for business on your mobile phone or computer. Includes one-time purchases and subscriptions.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                15 => [
                    'id' => 16,
                    'name' => 'Depreciation Expense',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'The amount of depreciation reported on the income statement. To determine the appropriate depreciation expense for a period, estimate the average useful life of the fixed asset in question. For example, if you paid $1,800 for a computer for your business, and the computer has an estimated useful life of 3 years, each monthly income statement will report a depreciation expense of $50 for 36 months.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                16 => [
                    'id' => 17,
                    'name' => 'Dues & Subscriptions',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Fees or dues you pay to professional, business, and civic organizations. Does not include business licenses and permits or business memberships.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                17 => [
                    'id' => 18,
                    'name' => 'Education & Training',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Education and training for yourself or your staff that directly relates to your business, including annual courses to maintain a professional designation, or required safety certifications.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                18 => [
                    'id' => 19,
                    'name' => 'Insurance – General Liability',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Premiums that insure your business for things like general liability or workers compensation.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                19 => [
                    'id' => 20,
                    'name' => 'Insurance – Vehicles',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Insurance for the vehicle you use for business.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                20  => [
                    'id' => 21,
                    'name' => 'Interest Expense',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Interest your business pays on loans and other forms of debt, including business loans, credit cards, mortgages, and vehicle payments.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                21 => [
                    'id' => 22,
                    'name' => 'Meals and Entertainment',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Food and beverages you consume while conducting business, with clients and vendors, or entertaining customers.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                22 => [
                    'id' => 23,
                    'name' => 'Office Supplies',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Office supplies and services for your business office or space.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                23 => [
                    'id' => 24,
                    'name' => 'Professional Fees',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Fees you pay to consultants or trained professionals for advice or services related to your business.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                24 => [
                    'id' => 25,
                    'name' => 'Rent Expense',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Costs to rent or lease property or furniture for your business office space. Does not include equipment rentals.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                25 => [
                    'id' => 26,
                    'name' => 'Repairs & Maintenance',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Repair and upkeep of property or equipment, as long as the repair doesn\'t add value to the property. Does not include replacements or upgrades.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                26 => [
                    'id' => 27,
                    'name' => 'Telephone – Land Line',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Land line phone services for your business.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                27 => [
                    'id' => 28,
                    'name' => 'Telephone – Wireless',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Mobile phone services for your business.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                28 => [
                    'id' => 29,
                    'name' => 'Travel Expense',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Transportation and travel costs while traveling for business. Does not include daily commute costs.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                29 => [
                    'id' => 30,
                    'name' => 'Utilities',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Utilities (electricity, water, etc.) for your business office. Does not include phone use.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                30 => [
                    'id' => 31,
                    'name' => 'Vehicle – Fuel',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Gas and fuel costs when driving for business.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                31 => [
                    'id' => 32,
                    'name' => 'Vehicle – Repairs & Maintenance',
                    'chart_of_accounts_subtypes_id' => '17',
                    'code' => null,
                    'description' => 'Repairs and preventative maitenance of the vehicle you drive for business.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                32 => [
                    'id' => 33,
                    'name' => 'Cost of Sale',
                    'chart_of_accounts_subtypes_id' => '18',
                    'code' => null,
                    'description' => '',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                33 => [
                    'id' => 34,
                    'name' => 'Payroll – Employee Benefits',
                    'chart_of_accounts_subtypes_id' => '20',
                    'code' => null,
                    'description' => 'Deductions taken from an employee\'s pay, like employment insurance. These are usually described as line deductions on the pay stub.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                34 => [
                    'id' => 35,
                    'name' => 'Payroll – Employer\'s Share of Benefits',
                    'chart_of_accounts_subtypes_id' => '20',
                    'code' => null,
                    'description' => 'Obligations your business is responsible for paying as an employer.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                35 => [
                    'id' => 36,
                    'name' => 'Payroll – Salary & Wages',
                    'chart_of_accounts_subtypes_id' => '20',
                    'code' => null,
                    'description' => 'Wages and salaries paid to your employees.',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                36 => [
                    'id' => 37,
                    'name' => 'Uncategorized Expense',
                    'chart_of_accounts_subtypes_id' => '21',
                    'code' => null,
                    'description' => 'A business cost you haven\'t categorized yet. Categorize it now to keep your records accurate.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
                37 => [
                    'id' => 38,
                    'name' => 'Loss on Foreign Exchange',
                    'chart_of_accounts_subtypes_id' => '22',
                    'code' => null,
                    'description' => 'Foreign exchange losses happen when the exchange rate between your business\'s home currency and a foreign currency transaction changes and results in a loss. This can happen in the time between a transaction being entered in Anvil and being settled, for example, between when you send an invoice and when your customer pays it. This can affect foreign currency invoice payments, bill payments, or foreign currency held in your bank account.	',
                    'created_at' => null,
                    'updated_at' => null,
                ],
            ]
        );
    }
}
